// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5013' | (string & {});
};

export type ActiveCalendar = {
    calendarId?: string | null;
};

export const AuthProvider = {
    GOOGLE: 'Google',
    PASSWORD: 'Password'
} as const;

export type AuthProvider = typeof AuthProvider[keyof typeof AuthProvider];

export type AuthProviderResponse = {
    authProvider?: AuthProvider;
};

export type BasicPerformanceStatistik = {
    kills?: number;
    deaths?: number;
    assists?: number;
    damage?: number;
    kdRatio?: number;
    adr?: number;
    krRatio?: number;
    headshots?: number;
    headshotPercentage?: number;
    doubleKills?: number;
    tripleKills?: number;
    quadroKills?: number;
    pentaKills?: number;
};

export type CalendarAnalysis = {
    averageEventsPerDay?: number;
    averageEventLength?: number;
    daysWithoutEvents?: number;
    eventActivityByHourDistribution?: {
        [key: string]: number;
    } | null;
    eventActivityByWeekdayDistribution?: {
        Sunday?: number;
        Monday?: number;
        Tuesday?: number;
        Wednesday?: number;
        Thursday?: number;
        Friday?: number;
        Saturday?: number;
    } | null;
    readonly performanceByEventCount?: {
        [key: string]: BasicPerformanceStatistik;
    } | null;
    readonly performanceByEventDuration?: {
        [key: string]: BasicPerformanceStatistik;
    } | null;
    readonly performanceByTimeSinceLastEvent?: {
        [key: string]: BasicPerformanceStatistik;
    } | null;
};

export type LoginGoogleRequest = {
    idToken?: string | null;
};

export type LoginRequest = {
    email?: string | null;
    password?: string | null;
};

export type LoginResponse = {
    token?: string | null;
    user?: User;
};

export type MatchAnalysis = {
    averageMatchesPerDay?: number;
    matchesPerDayDistribution?: {
        [key: string]: number;
    } | null;
    averageTimeBetweenMatches?: number;
    averageMatchDuration?: number;
    activityByHourDistribution?: {
        [key: string]: number;
    } | null;
    activityByWeekdayDistribution?: {
        Sunday?: number;
        Monday?: number;
        Tuesday?: number;
        Wednesday?: number;
        Thursday?: number;
        Friday?: number;
        Saturday?: number;
    } | null;
    readonly totalMatchCount?: number;
    readonly performanceByMatchesPerDay?: {
        [key: string]: BasicPerformanceStatistik;
    } | null;
};

export const Origin = {
    API: 'API',
    I_CALENDAR: 'ICalendar'
} as const;

export type Origin = typeof Origin[keyof typeof Origin];

export type PerformanceAnalysis = {
    averageKd?: number;
    averageAdr?: number;
    winrate?: number;
    averageKillsPerMatch?: number;
    averageDeathsPerMatch?: number;
    performanceByWeekdayDistribution?: {
        Sunday?: BasicPerformanceStatistik;
        Monday?: BasicPerformanceStatistik;
        Tuesday?: BasicPerformanceStatistik;
        Wednesday?: BasicPerformanceStatistik;
        Thursday?: BasicPerformanceStatistik;
        Friday?: BasicPerformanceStatistik;
        Saturday?: BasicPerformanceStatistik;
    } | null;
    readonly performanceByHourDistribution?: {
        [key: string]: BasicPerformanceStatistik;
    } | null;
    averagePerfomance?: BasicPerformanceStatistik;
};

export type Player = {
    player_id: string | null;
    nickname: string | null;
    avatar?: string | null;
    steam_nickname?: string | null;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type SessionAnalysis = {
    matchesPerSessionDistribution?: {
        [key: string]: number;
    } | null;
    averageMatchesPerSession?: number;
    averageTimeBetweenMatchesInSession?: number;
    averageTimeBetweenSessions?: number;
    readonly breakTime?: number;
    readonly performanceByMatchIndexSession?: {
        [key: string]: BasicPerformanceStatistik;
    } | null;
};

export type User = {
    id?: number;
    userName?: string | null;
    email?: string | null;
    readonly createdAt?: string;
};

export type UserCalendarResponse = {
    id?: string | null;
    description?: string | null;
    origin?: Origin;
};

export type UserRegisterRequest = {
    userName?: string | null;
    email?: string | null;
    password?: string | null;
};

export type UserUpdatePassword = {
    currentPassword?: string | null;
    newPassword?: string | null;
};

export type CalendarAnalysisWritable = {
    averageEventsPerDay?: number;
    averageEventLength?: number;
    daysWithoutEvents?: number;
    eventActivityByHourDistribution?: {
        [key: string]: number;
    } | null;
    eventActivityByWeekdayDistribution?: {
        Sunday?: number;
        Monday?: number;
        Tuesday?: number;
        Wednesday?: number;
        Thursday?: number;
        Friday?: number;
        Saturday?: number;
    } | null;
};

export type MatchAnalysisWritable = {
    averageMatchesPerDay?: number;
    matchesPerDayDistribution?: {
        [key: string]: number;
    } | null;
    averageTimeBetweenMatches?: number;
    averageMatchDuration?: number;
    activityByHourDistribution?: {
        [key: string]: number;
    } | null;
    activityByWeekdayDistribution?: {
        Sunday?: number;
        Monday?: number;
        Tuesday?: number;
        Wednesday?: number;
        Thursday?: number;
        Friday?: number;
        Saturday?: number;
    } | null;
};

export type PerformanceAnalysisWritable = {
    averageKd?: number;
    averageAdr?: number;
    winrate?: number;
    averageKillsPerMatch?: number;
    averageDeathsPerMatch?: number;
    performanceByWeekdayDistribution?: {
        Sunday?: BasicPerformanceStatistik;
        Monday?: BasicPerformanceStatistik;
        Tuesday?: BasicPerformanceStatistik;
        Wednesday?: BasicPerformanceStatistik;
        Thursday?: BasicPerformanceStatistik;
        Friday?: BasicPerformanceStatistik;
        Saturday?: BasicPerformanceStatistik;
    } | null;
    averagePerfomance?: BasicPerformanceStatistik;
};

export type SessionAnalysisWritable = {
    matchesPerSessionDistribution?: {
        [key: string]: number;
    } | null;
    averageMatchesPerSession?: number;
    averageTimeBetweenMatchesInSession?: number;
    averageTimeBetweenSessions?: number;
};

export type UserWritable = {
    id?: number;
    userName?: string | null;
    email?: string | null;
};

export type PostApiAnalysisData = {
    body?: never;
    path?: never;
    query?: {
        startDate?: string;
        endDate?: string;
    };
    url: '/api/Analysis';
};

export type PostApiAnalysisErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiAnalysisError = PostApiAnalysisErrors[keyof PostApiAnalysisErrors];

export type PostApiAnalysisResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiAnalysisResponse = PostApiAnalysisResponses[keyof PostApiAnalysisResponses];

export type GetApiAnalysisMatchData = {
    body?: never;
    path?: never;
    query?: {
        startDate?: string;
        endDate?: string;
    };
    url: '/api/Analysis/match';
};

export type GetApiAnalysisMatchErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiAnalysisMatchError = GetApiAnalysisMatchErrors[keyof GetApiAnalysisMatchErrors];

export type GetApiAnalysisMatchResponses = {
    /**
     * OK
     */
    200: MatchAnalysis;
};

export type GetApiAnalysisMatchResponse = GetApiAnalysisMatchResponses[keyof GetApiAnalysisMatchResponses];

export type GetApiAnalysisSessionData = {
    body?: never;
    path?: never;
    query?: {
        startDate?: string;
        endDate?: string;
    };
    url: '/api/Analysis/session';
};

export type GetApiAnalysisSessionErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiAnalysisSessionError = GetApiAnalysisSessionErrors[keyof GetApiAnalysisSessionErrors];

export type GetApiAnalysisSessionResponses = {
    /**
     * OK
     */
    200: SessionAnalysis;
};

export type GetApiAnalysisSessionResponse = GetApiAnalysisSessionResponses[keyof GetApiAnalysisSessionResponses];

export type GetApiAnalysisPerformanceData = {
    body?: never;
    path?: never;
    query?: {
        startDate?: string;
        endDate?: string;
    };
    url: '/api/Analysis/performance';
};

export type GetApiAnalysisPerformanceErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiAnalysisPerformanceError = GetApiAnalysisPerformanceErrors[keyof GetApiAnalysisPerformanceErrors];

export type GetApiAnalysisPerformanceResponses = {
    /**
     * OK
     */
    200: PerformanceAnalysis;
};

export type GetApiAnalysisPerformanceResponse = GetApiAnalysisPerformanceResponses[keyof GetApiAnalysisPerformanceResponses];

export type GetApiAnalysisCalendarData = {
    body?: never;
    path?: never;
    query?: {
        startDate?: string;
        endDate?: string;
    };
    url: '/api/Analysis/calendar';
};

export type GetApiAnalysisCalendarErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiAnalysisCalendarError = GetApiAnalysisCalendarErrors[keyof GetApiAnalysisCalendarErrors];

export type GetApiAnalysisCalendarResponses = {
    /**
     * OK
     */
    200: CalendarAnalysis;
};

export type GetApiAnalysisCalendarResponse = GetApiAnalysisCalendarResponses[keyof GetApiAnalysisCalendarResponses];

export type PostApiAuthLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/login';
};

export type PostApiAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type PostApiAuthRegisterData = {
    body?: UserRegisterRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/register';
};

export type PostApiAuthRegisterErrors = {
    /**
     * Conflict
     */
    409: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiAuthRegisterError = PostApiAuthRegisterErrors[keyof PostApiAuthRegisterErrors];

export type PostApiAuthRegisterResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthRegisterResponse = PostApiAuthRegisterResponses[keyof PostApiAuthRegisterResponses];

export type PostApiAuthRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/refresh';
};

export type PostApiAuthRefreshErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiAuthRefreshError = PostApiAuthRefreshErrors[keyof PostApiAuthRefreshErrors];

export type PostApiAuthRefreshResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthRefreshResponse = PostApiAuthRefreshResponses[keyof PostApiAuthRefreshResponses];

export type PostApiAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/logout';
};

export type PostApiAuthLogoutErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiAuthLogoutError = PostApiAuthLogoutErrors[keyof PostApiAuthLogoutErrors];

export type PostApiAuthLogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiAuthLogoutResponse = PostApiAuthLogoutResponses[keyof PostApiAuthLogoutResponses];

export type PostApiAuthPasswordData = {
    body?: UserUpdatePassword;
    path?: never;
    query?: never;
    url: '/api/Auth/password';
};

export type PostApiAuthPasswordErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostApiAuthPasswordError = PostApiAuthPasswordErrors[keyof PostApiAuthPasswordErrors];

export type PostApiAuthPasswordResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiAuthPasswordResponse = PostApiAuthPasswordResponses[keyof PostApiAuthPasswordResponses];

export type PostApiAuthGoogleData = {
    body?: LoginGoogleRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/google';
};

export type PostApiAuthGoogleErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiAuthGoogleError = PostApiAuthGoogleErrors[keyof PostApiAuthGoogleErrors];

export type PostApiAuthGoogleResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthGoogleResponse = PostApiAuthGoogleResponses[keyof PostApiAuthGoogleResponses];

export type GetApiAuthAuthProviderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/AuthProvider';
};

export type GetApiAuthAuthProviderErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiAuthAuthProviderError = GetApiAuthAuthProviderErrors[keyof GetApiAuthAuthProviderErrors];

export type GetApiAuthAuthProviderResponses = {
    /**
     * OK
     */
    200: AuthProviderResponse;
};

export type GetApiAuthAuthProviderResponse = GetApiAuthAuthProviderResponses[keyof GetApiAuthAuthProviderResponses];

export type GetApiAuthGoogleCalendarData = {
    body?: never;
    path?: never;
    query?: {
        redirectUri?: string;
    };
    url: '/api/Auth/google-calendar';
};

export type GetApiAuthGoogleCalendarErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiAuthGoogleCalendarError = GetApiAuthGoogleCalendarErrors[keyof GetApiAuthGoogleCalendarErrors];

export type GetApiAuthGoogleCalendarResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetApiAuthGoogleCalendarResponse = GetApiAuthGoogleCalendarResponses[keyof GetApiAuthGoogleCalendarResponses];

export type GetApiAuthGoogleCalendarCallbackData = {
    body?: never;
    path?: never;
    query?: {
        code?: string;
        state?: string;
    };
    url: '/api/Auth/google-calendar/callback';
};

export type GetApiAuthGoogleCalendarCallbackErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiAuthGoogleCalendarCallbackError = GetApiAuthGoogleCalendarCallbackErrors[keyof GetApiAuthGoogleCalendarCallbackErrors];

export type GetApiAuthGoogleCalendarCallbackResponses = {
    /**
     * OK
     */
    200: AuthProviderResponse;
};

export type GetApiAuthGoogleCalendarCallbackResponse = GetApiAuthGoogleCalendarCallbackResponses[keyof GetApiAuthGoogleCalendarCallbackResponses];

export type GetApiOAuthGoogleCalendarCalendarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/OAuth/google-calendar/calendars';
};

export type GetApiOAuthGoogleCalendarCalendarsErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOAuthGoogleCalendarCalendarsError = GetApiOAuthGoogleCalendarCalendarsErrors[keyof GetApiOAuthGoogleCalendarCalendarsErrors];

export type GetApiOAuthGoogleCalendarCalendarsResponses = {
    /**
     * OK
     */
    200: Array<UserCalendarResponse>;
};

export type GetApiOAuthGoogleCalendarCalendarsResponse = GetApiOAuthGoogleCalendarCalendarsResponses[keyof GetApiOAuthGoogleCalendarCalendarsResponses];

export type PostApiOAuthGoogleCalendarCalendarsData = {
    body?: {
        files?: Array<Blob | File>;
    };
    path?: never;
    query?: never;
    url: '/api/OAuth/google-calendar/calendars';
};

export type PostApiOAuthGoogleCalendarCalendarsErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PostApiOAuthGoogleCalendarCalendarsError = PostApiOAuthGoogleCalendarCalendarsErrors[keyof PostApiOAuthGoogleCalendarCalendarsErrors];

export type PostApiOAuthGoogleCalendarCalendarsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PostApiOAuthGoogleCalendarCalendarsResponse = PostApiOAuthGoogleCalendarCalendarsResponses[keyof PostApiOAuthGoogleCalendarCalendarsResponses];

export type GetApiOAuthGoogleCalendarCalendarsActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/OAuth/google-calendar/calendars/active';
};

export type GetApiOAuthGoogleCalendarCalendarsActiveErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOAuthGoogleCalendarCalendarsActiveError = GetApiOAuthGoogleCalendarCalendarsActiveErrors[keyof GetApiOAuthGoogleCalendarCalendarsActiveErrors];

export type GetApiOAuthGoogleCalendarCalendarsActiveResponses = {
    /**
     * OK
     */
    200: Array<ActiveCalendar>;
};

export type GetApiOAuthGoogleCalendarCalendarsActiveResponse = GetApiOAuthGoogleCalendarCalendarsActiveResponses[keyof GetApiOAuthGoogleCalendarCalendarsActiveResponses];

export type PutApiOAuthGoogleCalendarCalendarsActiveData = {
    body?: Array<ActiveCalendar>;
    path?: never;
    query?: never;
    url: '/api/OAuth/google-calendar/calendars/active';
};

export type PutApiOAuthGoogleCalendarCalendarsActiveErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PutApiOAuthGoogleCalendarCalendarsActiveError = PutApiOAuthGoogleCalendarCalendarsActiveErrors[keyof PutApiOAuthGoogleCalendarCalendarsActiveErrors];

export type PutApiOAuthGoogleCalendarCalendarsActiveResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOAuthGoogleCalendarCalendarsActiveResponse = PutApiOAuthGoogleCalendarCalendarsActiveResponses[keyof PutApiOAuthGoogleCalendarCalendarsActiveResponses];

export type GetApiOAuthGoogleCalendarStateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/OAuth/google-calendar/state';
};

export type GetApiOAuthGoogleCalendarStateErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOAuthGoogleCalendarStateError = GetApiOAuthGoogleCalendarStateErrors[keyof GetApiOAuthGoogleCalendarStateErrors];

export type GetApiOAuthGoogleCalendarStateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type GetApiOAuthGoogleCalendarStateResponse = GetApiOAuthGoogleCalendarStateResponses[keyof GetApiOAuthGoogleCalendarStateResponses];

export type DeleteApiOAuthGoogleCalendarData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/OAuth/google-calendar';
};

export type DeleteApiOAuthGoogleCalendarErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiOAuthGoogleCalendarError = DeleteApiOAuthGoogleCalendarErrors[keyof DeleteApiOAuthGoogleCalendarErrors];

export type DeleteApiOAuthGoogleCalendarResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiOAuthGoogleCalendarResponse = DeleteApiOAuthGoogleCalendarResponses[keyof DeleteApiOAuthGoogleCalendarResponses];

export type GetApiOAuthFaceitPlayersSearchData = {
    body?: never;
    path?: never;
    query?: {
        nickname?: string;
        offset?: number;
        limit?: number;
    };
    url: '/api/OAuth/faceit/players/search';
};

export type GetApiOAuthFaceitPlayersSearchErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOAuthFaceitPlayersSearchError = GetApiOAuthFaceitPlayersSearchErrors[keyof GetApiOAuthFaceitPlayersSearchErrors];

export type GetApiOAuthFaceitPlayersSearchResponses = {
    /**
     * OK
     */
    200: Array<Player>;
};

export type GetApiOAuthFaceitPlayersSearchResponse = GetApiOAuthFaceitPlayersSearchResponses[keyof GetApiOAuthFaceitPlayersSearchResponses];

export type PutApiOAuthFaceitPlayersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/OAuth/faceit/players/{id}';
};

export type PutApiOAuthFaceitPlayersByIdErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type PutApiOAuthFaceitPlayersByIdError = PutApiOAuthFaceitPlayersByIdErrors[keyof PutApiOAuthFaceitPlayersByIdErrors];

export type PutApiOAuthFaceitPlayersByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiOAuthFaceitPlayersByIdResponse = PutApiOAuthFaceitPlayersByIdResponses[keyof PutApiOAuthFaceitPlayersByIdResponses];

export type DeleteApiOAuthFaceitPlayersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/OAuth/faceit/players';
};

export type DeleteApiOAuthFaceitPlayersErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type DeleteApiOAuthFaceitPlayersError = DeleteApiOAuthFaceitPlayersErrors[keyof DeleteApiOAuthFaceitPlayersErrors];

export type DeleteApiOAuthFaceitPlayersResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiOAuthFaceitPlayersResponse = DeleteApiOAuthFaceitPlayersResponses[keyof DeleteApiOAuthFaceitPlayersResponses];

export type GetApiOAuthFaceitPlayersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/OAuth/faceit/players';
};

export type GetApiOAuthFaceitPlayersErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOAuthFaceitPlayersError = GetApiOAuthFaceitPlayersErrors[keyof GetApiOAuthFaceitPlayersErrors];

export type GetApiOAuthFaceitPlayersResponses = {
    /**
     * OK
     */
    200: Player;
};

export type GetApiOAuthFaceitPlayersResponse = GetApiOAuthFaceitPlayersResponses[keyof GetApiOAuthFaceitPlayersResponses];

export type GetApiOAuthFaceitMatchesStateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/OAuth/faceit/matches/state';
};

export type GetApiOAuthFaceitMatchesStateErrors = {
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiOAuthFaceitMatchesStateError = GetApiOAuthFaceitMatchesStateErrors[keyof GetApiOAuthFaceitMatchesStateErrors];

export type GetApiOAuthFaceitMatchesStateResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GetApiOAuthFaceitMatchesStateResponse = GetApiOAuthFaceitMatchesStateResponses[keyof GetApiOAuthFaceitMatchesStateResponses];

export type DeleteApiUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users/me';
};

export type DeleteApiUsersMeErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type DeleteApiUsersMeError = DeleteApiUsersMeErrors[keyof DeleteApiUsersMeErrors];

export type DeleteApiUsersMeResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiUsersMeResponse = DeleteApiUsersMeResponses[keyof DeleteApiUsersMeResponses];

export type GetApiUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Users/me';
};

export type GetApiUsersMeErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Internal Server Error
     */
    500: ProblemDetails;
};

export type GetApiUsersMeError = GetApiUsersMeErrors[keyof GetApiUsersMeErrors];

export type GetApiUsersMeResponses = {
    /**
     * OK
     */
    200: User;
};

export type GetApiUsersMeResponse = GetApiUsersMeResponses[keyof GetApiUsersMeResponses];
