// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using g_map_compare_backend.Data;

#nullable disable

namespace PlayPredictorWebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260320144113_EventDescriptionOptional")]
    partial class EventDescriptionOptional
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayPredictorWebAPI.Models.Analysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SessionPerformanceId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Analyses");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalendarId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastEndDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastStartDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SyncToken")
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.CalendarEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("End")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EndTimeUnspecified")
                        .HasColumnType("boolean");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("CalendarEvents");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.ExternalOAuthAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderUserId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExternalOAuthAccounts");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.FaceitAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("FaceitAccounts");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.FeaturedMatchSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("FeaturedMatchSessions");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.Match", b =>
                {
                    b.Property<int>("FaceitAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("MatchId")
                        .HasColumnType("text");

                    b.Property<double>("Adr")
                        .HasColumnType("double precision");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<int>("DoubleKills")
                        .HasColumnType("integer");

                    b.Property<int>("FinalScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FirstHalfScore")
                        .HasColumnType("integer");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("HeadshotPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("Headshots")
                        .HasColumnType("integer");

                    b.Property<double>("KdRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<double>("KrRatio")
                        .HasColumnType("double precision");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mvps")
                        .HasColumnType("integer");

                    b.Property<int>("OvertimeScore")
                        .HasColumnType("integer");

                    b.Property<int>("PentaKills")
                        .HasColumnType("integer");

                    b.Property<int>("QuadroKills")
                        .HasColumnType("integer");

                    b.Property<int>("Rounds")
                        .HasColumnType("integer");

                    b.Property<string>("Score")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SecondHalfScore")
                        .HasColumnType("integer");

                    b.Property<int>("TripleKills")
                        .HasColumnType("integer");

                    b.Property<bool>("Won")
                        .HasColumnType("boolean");

                    b.HasKey("FaceitAccountId", "MatchId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptedAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasColumnType("text");

                    b.Property<int>("ExternalOAuthAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalOAuthAccountId")
                        .IsUnique();

                    b.ToTable("OAuthTokens");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.SessionPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnalysisId")
                        .HasColumnType("integer");

                    b.Property<double>("Kd")
                        .HasColumnType("double precision");

                    b.Property<string>("PerformanceClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PerformanceScore")
                        .HasColumnType("double precision");

                    b.Property<double>("RelativeAdr")
                        .HasColumnType("double precision");

                    b.Property<double>("RelativeKd")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisId");

                    b.ToTable("SessionPerformances");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.Analysis", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.User", "User")
                        .WithMany("Analyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.Calendar", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.User", "User")
                        .WithMany("Calendars")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.CalendarEvent", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.Calendar", "Calendar")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.ExternalOAuthAccount", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.User", "User")
                        .WithMany("ExternalAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.FaceitAccount", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.User", "User")
                        .WithOne("FaceitAccount")
                        .HasForeignKey("PlayPredictorWebAPI.Models.FaceitAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.FeaturedMatchSession", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.Analysis", "Analysis")
                        .WithMany("FeaturedMatchSessions")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.Match", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.FaceitAccount", "FaceitAccount")
                        .WithMany("Matches")
                        .HasForeignKey("FaceitAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaceitAccount");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.OAuthToken", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.ExternalOAuthAccount", "ExternalOAuthAccount")
                        .WithOne("Token")
                        .HasForeignKey("PlayPredictorWebAPI.Models.OAuthToken", "ExternalOAuthAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalOAuthAccount");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.SessionPerformance", b =>
                {
                    b.HasOne("PlayPredictorWebAPI.Models.Analysis", "Analysis")
                        .WithMany("SessionPerformances")
                        .HasForeignKey("AnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.Analysis", b =>
                {
                    b.Navigation("FeaturedMatchSessions");

                    b.Navigation("SessionPerformances");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.Calendar", b =>
                {
                    b.Navigation("CalendarEvents");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.ExternalOAuthAccount", b =>
                {
                    b.Navigation("Token");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.FaceitAccount", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("PlayPredictorWebAPI.Models.User", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Calendars");

                    b.Navigation("ExternalAccounts");

                    b.Navigation("FaceitAccount")
                        .IsRequired();

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
