import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import InitAuth from "@/components/InitAuth/InitAuth";
import { Toaster } from "@/components/ui/toaster"


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {

	return (
		<html lang="en" suppressHydrationWarning>
			<body
				style={{ height: "100vh" }}
			>

				<Provider>
					<InitAuth>
						{children}
					</InitAuth>
					<Toaster />
				</Provider>
			</body>
			<script src="https://accounts.google.com/gsi/client" async defer></script>
		</html>
	);
}
